<div id="chart_div"></div>
<div id="table-container"></div>
<div id="popup-container" class="popup-container">
    <div id="popup-content" class="popup-content">
        <!-- Pop-up content will be displayed here -->
    </div>
    <span id="close-btn" class="close-btn">&times;</span>
</div>

<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
<?php echo $this->getJsObjectName() ?> = new varienGridCompare("<?php echo $this->getUrl('*/*/grid'); ?>", "<?php echo $this->getUrl('*/*/metric'); ?>");
</script>
