<form method="POST" action="<?php echo $this->getUrl('admin/user/login') ?>">
    <section>
        <div class="signin">
            <div class="content">
                <h2>Admin</h2>
                <div class="form">
                    <div class="inputBox">
                        <input type="email" name="login[customer_email]" id="loginemail" autocomplete="off"
                            required><i>Username</i>
                    </div>
                    <div class="inputBox">
                        <input type="password" name="login[password]" id="loginpass" required><i>Password</i>
                    </div>
                    <div class="inputBox">
                        <input type="submit" value="Login">
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</form>