<?php
$ticket = $this->getTicket();
$ticketId = $ticket->getTicketId();
$currentUser = $this->getCurrentUser();
$comments = $this->getCommentData();
?>
Complete Comments:<select id="show_hide">
    <option value='true'>Show</option>
    <option value='false'>Hide</option>
</select><br><br>
<?php
function renderComments($comments, $ticketId, $currentUser)
{
    foreach ($comments as $comment):
        ?>
        <tr data-comment-id="<?php echo $comment['comment_id']; ?>">
            <?php if ($comment['is_question'] == 1) { ?>
                <td colspan="<?php echo $comment['level'] ?>" ></td>
                <td>
                <?php } else { ?>
                <td rowspan="<?php echo $comment['rowspan'] ?>">
                <?php } ?>
                User ID:<?php echo $comment['user_id']; ?><br>
                Comment Id:<?php echo $comment['comment_id']; ?><br>
                Comment:<?php echo $comment['comment']; ?><br>
            </td>
            <?php if($comment['is_completed']=='Completed' && empty($comment['replies'])):?>
                <td style="background-color:#dbb8b8;;">Completed</td>
            <?php endif?>
            <?php if ($comment['is_locked'] == 'Unlocked' && $comment['is_completed'] !='Completed'): ?>
                    <td>
                        <button button-comment-id="<?php echo $comment['comment_id']; ?>"
                            onclick="addReplyButton(<?php echo $comment['comment_id']; ?>,<?php echo $ticketId ?>,<?php echo $currentUser ?>)">Reply</button>
                        <?php if(empty($comment['replies'])): ?>
                            <button data-comment-id="<?php echo $comment['comment_id']; ?>"
                                onclick="completeComment(<?php echo $comment['comment_id']; ?>,<?php echo $ticketId ?>)">Complete</button>
                        <?php endif; ?>
                    </td>
            <?php endif; ?>
        </tr>
        <?php
        if(!empty($comment['replies'])):
            renderComments($comment['replies'], $ticketId, $currentUser);
        endif;
    endforeach;
}
?>
<table border="2px solid #cc8585" style="width: 100%;">
    <?php renderComments($comments, $ticketId, $currentUser); ?>
</table>
<button onclick="savelock(<?php echo $this->getLocklevel() ?>,<?php echo $ticketId ?>)">Lock</button>
<div id="question">
    <button onclick="addQue(<?php echo $this->getLocklevel() ?>,<?php echo $ticketId ?>,<?php echo $currentUser ?>)">Add
        Question</button>
</div>
<script>
    var saveLockUrl = '<?php echo $this->getUrl('*/*/saveLock') ?>';
    var savecommentUrl = '<?php echo $this->getUrl('*/*/saveChildComment') ?>';
    var saveCompleteUrl = '<?php echo $this->getUrl('*/*/saveComplete') ?>';
    var saveQueUrl = '<?php echo $this->getUrl('*/*/saveQuestion') ?>';
</script>