<?php
$ticket = $this->getTicket();
$ticketId = $ticket->getTicketId();
$currentUser = $this->getCurrentUser();
$comments = $this->getCommentData();
$currentLevel = $this->getLocklevel();

?>
<table>
    <tr>
        <th>Ticket Id</th>
        <td><?php echo $ticket->getId(); ?></td>
    </tr>
    <tr>
        <th>Title</th>
        <td class="title"><?php echo $ticket->getTitle(); ?></td>
    </tr>
    <tr>
        <th>Description</th>
        <td class="description"><?php echo $ticket->getDescription(); ?></td>
    </tr>
    <tr>
        <th>Assign By</th>
        <td>
            <select name="assign_by" onchange="save(this.value,<?php echo $ticket->getId() ?>,'assign_by')">
                <?php foreach ($this->getUserCollection() as $user) { ?>
                    <option value="<?php echo $user->getUserId() ?>" <?php if ($user->getUserId() == $ticket->getAssignBy())
                           echo 'selected'; ?>><?php echo $user->getUsername() ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <th>Assign To</th>
        <td>
            <select name="assign_to" onchange="save(this.value,<?php echo $ticket->getId() ?>,'assign_to')">
                <?php foreach ($this->getUserCollection() as $user) { ?>
                    <option value="<?php echo $user->getUserId() ?>" <?php if ($user->getUserId() == $ticket->getAssignTO())
                           echo 'selected'; ?>><?php echo $user->getUsername() ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <th>Priority</th>
        <td class="priority"><?php echo $ticket->getPriority(); ?></td>
    </tr>
    <?php
    $statusData = $this->getStatusData($ticket->getStatus());
    $statusColor = $statusData->getColourCode();
    ?>
    <tr>
        <th>Status</th>
        <td class="status_code" id="status_code" style="background-color: <?php echo $statusColor; ?>;">
            <select name="status_code" onchange="save(this.value,<?php echo $ticket->getId(); ?>,'status')">
                <?php foreach ($this->getStatusArray() as $status) { ?>
                    <option value="<?php echo $status->getStatusCode(); ?>" <?php if ($status->getStatusCode() == $ticket->getStatus())
                           echo 'selected'; ?>><?php echo $status->getStatusLabel(); ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    </tr>
</table>
<div id="comment_form">
    <form action="<?php echo Mage::getUrl('adminhtml/ticket/savecomment') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey') ?>
        <textarea id="comment" rows="10" cols="50" name="comment"></textarea>
        <input type="hidden" value="<?php echo $ticket->getId() ?>" name="ticket_id">
        <input type="hidden" value="<?php echo $this->getCurrentUser() ?>" name="user_id">
        <button type="submit">Save</button>
    </form>
</div>
<table border="1">
    <?php
    function renderComments($comments, $ticketId, $currentUser)
    {
        foreach ($comments as $comment):
            ?>
            <tr data-comment-id="<?php echo $comment['comment_id']; ?>">
                <td rowspan="<?php echo $comment['rowspan'] ?>">
                    User ID:<?php echo $comment['user_id']; ?><br>
                    Comment Id:<?php echo $comment['comment_id']; ?><br>
                    Comment:<?php echo $comment['comment']; ?><br>
                </td>
                <?php if ($comment['is_locked'] == 1): ?>
                    <td>
                        <button data-comment-id="<?php echo $comment['comment_id']; ?>"
                            onclick="addReplyButton(<?php echo $comment['comment_id']; ?>,<?php echo $ticketId ?>,<?php echo $currentUser ?>)">Reply</button>
                        <?php if ($comment['is_completed'] == 1): ?>
                            <button data-comment-id="<?php echo $comment['comment_id']; ?>"
                                onclick="completeComment(<?php echo $comment['comment_id']; ?>)">Complete</button>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
            <?php
            if (!empty($comment['replies'])):
                ?>
                <tr>
                    <td>
                        <table border="1" style="width: 100%;">
                            <?php renderComments($comment['replies'], $ticketId, $currentUser); ?>
                        </table>
                    </td>
                </tr>
                <?php
            endif;
        endforeach;
    }
    ?>
</table>
<div id="comment_container">
    <table border="1" style="width: 100%;">
        <?php renderComments($comments, $ticketId, $currentUser); ?>
    </table>
</div>
<button onclick="savelock(<?php echo $currentLevel ?>)">Lock</button>
<div id="question">
    <button onclick="addQue(<?php echo $currentLevel ?>,<?php echo $currentUser ?>,<?php echo $ticketId ?>)">Add
        Question</button>
</div>
<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script>
    var url = '<?php echo $this->getUrl('*/*/update'); ?>';
    var savecommentUrl = '<?php echo $this->getUrl('*/*/savechildcomment') ?>';
    var saveLockUrl = '<?php echo $this->getUrl('*/*/savelock') ?>';
    var saveCompleteUrl = '<?php echo $this->getUrl('*/*/savecomplete') ?>';
    var saveQueUrl = '<?php echo $this->getUrl('*/*/savequestion') ?>'
</script>